# Individual Responsibility and Expectations

This course works best when we all function together as a team. You can find a detailed version of course policies in the fine print section of this syllabus, but the your responsibilities can be summed up as follows:

::: callout-important
## Key Summary - Individual responsibility:

-   Take responsibility for your own actions.
-   Be honest.
-   Respect yourself and everyone else! Zero tolerance for discrimination or harassment of any kind.
-   Don't do things in class that aren't related to class
-   If you need help of any kind, just ask!
:::

Additionally, we have several expectations of you:

•	To read and be familiar with the information contained in the course schedule, logistics, and packing lists.

•	To attend all field sessions unless absences are prior approved by the instructors.  

•	To become familiar with the Field Book for Describing and Sampling Soils

•	To ask questions. 

•	To work together collaboratively and respectfully in groups

•	To come prepared for class every day. Includes proper attire for fieldwork, rain gear, footwear, and your own lunch and drink when necessary (see schedule).

•	To notify us ahead of time if you cannot be present.  Please call or text my personal cell phone if you have any issues with the class.  

•	To actively participate in discussions in the field.

•	To complete and submit course evaluations. 

•	Be flexible.  This is a field course.  Depending on weather and other conditions we may have to make adjustments as necessary. 

•	Be respectful of the diversity of cultures, backgrounds, preferences, and thought of the students and instructors in the class. We all have different ways of approaching and solving problems and this course will be most effective when we honor and celebrate both our similarities and differences.

•	Bring motivation and a positive attitude!

•	Stay on task.  We have a lot to accomplish in a fairly short period of time.  Pay attention to the task at hand and take your work seriously.

•	Enjoy yourself!  Soils are fascinating to study and having the opportunity to spend time in the field with your peers and instructors can be a great experience.  It always is for me.

