# Introduction

You are about to embark on an extremely memorable field eperience, with tremendous learning potential, new colleagues and friends, and anew adventures in our beautiful state of Minnesota. 

Students participating in this course come from many different backgrounds and specialties Naturally, there will be wide variability in field experience and familiarity with soil science. Throughout the course please know that we all work to learn and experience together. 

## Course Objectives

**General Student Learning Outcomes / Course Learning Outcomes:**

•	Can identify, define, and solve problems
•	Have mastered a body of knowledge and a mode of inquiry
•	Can communicate effectively
•	Have acquired skills for effective citizenship and life-long learning.
•	Appreciation of differences by recognizing the value of interacting with individuals with backgrounds and/or perspectives different from their own. 
•	Tolerance of ambiguity by demonstrating the ability to perform in complicated environments where clear cut answers or standard operating procedures are absent

**More specifically, by the time you complete this course you should be able to:**

•	Accurately describe a soil profile including horizon delineation and identification, soil texture, color, consistence, structure, coarse fragments, and pH.
•	Accurately describe landscape characteristics affecting soil formation
•	Make general land-use interpretations from the soil profile and landscape descriptions
•	Classify soils of this region to the Great Group level based on a soil profile description
•	Participate in Soil Judging
•	Define a soil catena and explain its importance in understanding spatial patterns of soil variability.
•	Work effectively in a small group setting to describe soil profiles and landscapes and solve problems related to interpretations.
