# Course Logistics

## Travel

Transportation is provided from St. Paul campus for the entire course. Students are responsible for arranging transportation to and from the St. Paul campus. If you choose to drive your own vehicle this is possible, however please let the instructors know in advance.

## Grading

This course is graded based on participation.  We want everyone to do well! There are no formal exams or quizzes, so grades will be based on the following:

### A

- Pays attention during introductory instruction activities.

- Participation during all group learning activities in the classroom and field.

- Completing and turning in soil descriptions during all field activities each day.

### B

- Does not participate in one group learning activity or soil description.

### C

- Does not participate in two group learning activities or soil descriptions.

## Course Dates At-A-Glance

An brief overview of the schedule is provided below. For a detailed schedule, please see the Course Schedule section of this syllabus.

| Day | Date | Activity  |
|----|----|----|
| 1 | 18MAY | Drive from St. Paul to Jay Cooke State Park - set up camp |
| 2| 19MAY | Morning: Class introduction, team building. Afternoon - Fond du Lac Tribal and Community College, Introduction to Course Content, Texture Practice. |
| 3| 20MAY | Outwash Soils at Cloquet Forestry Center |
| 4| 21MAY | Coarse-loamy Rainy and Superior Lobe Till Soils|
| 5| 22MAY | Fine-textured Superior Lobe Till Soils|
| 6| 23MAY | Organic soils of the Glacial Lake Upham-Aitkin Basin, return to St Paul|
| 7| 26MAY | Drive from St Paul to Itasca Biological Station |
| 8| 27MAY | Soils of the North Central Hardwoods - Marcell Experimental Forest |
| 9| 28MAY | Soils and Forest Management - Chippewa National Forest |
| 10| 29MAY | Soils of the Forest-Prairie Transition |
| 11| 30MAY | Course wrap-up and return to St. Paul |






