# Policies

## Student Protections Statement

UAF embraces and grows a culture of respect, diversity, inclusion, and caring. Students at this university are protected against sexual harassment and discrimination (Title IX). Faculty members are designated as responsible employees which means they are required to report sexual misconduct. Graduate teaching assistants do not share the same reporting obligations. For more information on your rights as a student and the resources available to you to resolve problems, please go to the following site:

[https://catalog.uaf.edu/academics-regulations/students-rights-responsibilities/](https://catalog.uaf.edu/academics-regulations/students-rights-responsibilities/)

## Disabilities Services Statement

Instructors will work with the Office of Disability Services to provide reasonable accommodation to students with disabilities.

## Student Academic Support

- Speaking Center (907-474-5470, uaf-speakingcenter@alaska.edu, Gruening 507)

- Writing Center (907-474-5314, uaf-writing-center@alaska.edu, Gruening 8th
floor)

- UAF Math Services, uafmathstatlab@gmail.com, Chapman Building (for math fee
paying students only)

- Developmental Math Lab, Gruening 406

- The Debbie Moses Learning Center at CTC (907-455-2860, 604 Barnette St,
Room 120, https://www.ctc.uaf.edu/student-services/student-success-center/)

- For more information and resources, please see the Academic Advising
Resource List [https://www.uaf.edu/advising/lr/SKM_364e19011717281.pdf](https://www.uaf.edu/advising/lr/SKM_364e19011717281.pdf)

## Other Student Resources

- Disability Services (907-474-5655, uaf-disability-services@alaska.edu, Whitaker 208)

- Student Health & Counseling [6 free counseling sessions] (907-474-7043, https://www.uaf.edu/chc/appointments.php, Whitaker 203)

- Center for Student Rights and Responsibilities (907-474-7317, uaf-studentrights@alaska.edu, Eielson 110)

- Associated Students of the University of Alaska Fairbanks (ASUAF) or ASUAF Student Government (907-474-7355, asuaf.office@alaska.edu, Wood Center 119)

## Non-discrimination Statement

The University of Alaska is an affirmative action/equal opportunity employer and educational institution. The University of Alaska does not discriminate on the basis of race, religion, color, national origin, citizenship, age, sex, physical or mental disability, status as a protected veteran, marital status, changes in marital status, pregnancy, childbirth or related medical conditions, parenthood, sexual orientation, gender identity, political affiliation or belief, genetic information, or other legally protected status. The University's commitment to nondiscrimination, including against sex discrimination, applies to students, employees, and applicants for admission and employment. Contact information, applicable laws, and complaint procedures are included on UA's statement of nondiscrimination available at www.alaska.edu/nondiscrimination. For more information, contact:

UAF Department of Equity and Compliance
1692 Tok Lane, 3rd floor, Constitution Hall, Fairbanks, AK 99775 907-474-7300
uaf-deo@alaska.edu

- UA is an AA/EO employer and educational institution and prohibits illegal discrimination against any individual: www.alaska.edu/nondiscrimination.

- Incidents can be reported to your university’s Equity and Compliance office (listed below) or online reporting portal. University of Alaska takes immediate, effective, and appropriate action to respond to reported acts of discrimination and harassment.
        
- There are supportive measures available to individuals that may have experienced discrimination.

- University of Alaska’s Board of Regents’ Policy & University Regulations (UA BoR P&R) 01.02.020 Nondiscrimination and 01.04 Sex and Gender-Based Discrimination Under Title IX, go to: http://alaska.edu/bor/policy-regulations/.

- UA BoR P&R apply at all university owned or operated sites, university sanctioned events, clinical sites and during all academic or research related travel that are university sponsored.

- For further information on your rights and resources click [here](https://www.alaska.edu/accountability/).